# Generated by Django 5.2.8 on 2025-11-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
