# Generated by Django 5.2.8 on 2025-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
